# Auto-generated by compose2nix, secrets managed via clan vars.
{
  pkgs,
  lib,
  config,
  ...
}: let
  vars = config.clan.core.vars.generators.romm;
in {
  clan.core.vars.generators.romm = {
    share = true;
    files.romm-env.secret = true;
    files.romm-db-env.secret = true;
    prompts.db-password = {
      description = "RomM MariaDB user password";
      type = "hidden";
    };
    prompts.db-root-password = {
      description = "RomM MariaDB root password";
      type = "hidden";
    };
    prompts.auth-secret-key = {
      description = "RomM auth secret key";
      type = "hidden";
    };
    prompts.retroachievements-api-key = {
      description = "RetroAchievements API key";
      type = "hidden";
    };
    prompts.screenscraper-password = {
      description = "ScreenScraper password";
      type = "hidden";
    };
    script = ''
      cat > "$out/romm-env" <<EOF
      DB_PASSWD=$(cat "$prompts/db-password")
      ROMM_AUTH_SECRET_KEY=$(cat "$prompts/auth-secret-key")
      RETROACHIEVEMENTS_API_KEY=$(cat "$prompts/retroachievements-api-key")
      SCREENSCRAPER_PASSWORD=$(cat "$prompts/screenscraper-password")
      EOF

      cat > "$out/romm-db-env" <<EOF
      MARIADB_PASSWORD=$(cat "$prompts/db-password")
      MARIADB_ROOT_PASSWORD=$(cat "$prompts/db-root-password")
      EOF
    '';
  };

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."romm" = {
    image = "rommapp/romm:latest";
    environment = {
      "DB_HOST" = "romm-db";
      "DB_NAME" = "romm";
      "DB_USER" = "romm-user";
      "HASHEOUS_API_ENABLED" = "true";
      "SCREENSCRAPER_USER" = "sadbeast";
      "STEAMGRIDDB_API_KEY" = "";
    };
    environmentFiles = [
      vars.files.romm-env.path
    ];
    volumes = [
      "/mnt/files/media/config/romm/assets:/romm/assets:rw"
      "/mnt/files/media/config/romm/config:/romm/config:rw"
      "/mnt/files/media/library:/romm/library:rw"
      "romm_romm_redis_data:/redis-data:rw"
      "romm_romm_resources:/romm/resources:rw"
    ];
    ports = [
      "8080:8080/tcp"
    ];
    dependsOn = [
      "romm-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=romm"
      "--network=romm_default"
    ];
  };
  systemd.services."podman-romm" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-romm_default.service"
      "podman-volume-romm_romm_redis_data.service"
      "podman-volume-romm_romm_resources.service"
    ];
    requires = [
      "podman-network-romm_default.service"
      "podman-volume-romm_romm_redis_data.service"
      "podman-volume-romm_romm_resources.service"
    ];
    partOf = [
      "podman-compose-romm-root.target"
    ];
    wantedBy = [
      "podman-compose-romm-root.target"
    ];
  };
  virtualisation.oci-containers.containers."romm-db" = {
    image = "mariadb:latest";
    environment = {
      "MARIADB_DATABASE" = "romm";
      "MARIADB_USER" = "romm-user";
    };
    environmentFiles = [
      vars.files.romm-db-env.path
    ];
    volumes = [
      "romm_mysql_data:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"healthcheck.sh\", \"--connect\", \"--innodb_initialized\"]"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-start-period=30s"
      "--health-startup-interval=10s"
      "--health-timeout=5s"
      "--network-alias=romm-db"
      "--network=romm_default"
    ];
  };
  systemd.services."podman-romm-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-romm_default.service"
      "podman-volume-romm_mysql_data.service"
    ];
    requires = [
      "podman-network-romm_default.service"
      "podman-volume-romm_mysql_data.service"
    ];
    partOf = [
      "podman-compose-romm-root.target"
    ];
    wantedBy = [
      "podman-compose-romm-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-romm_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f romm_default";
    };
    script = ''
      podman network inspect romm_default || podman network create romm_default
    '';
    partOf = ["podman-compose-romm-root.target"];
    wantedBy = ["podman-compose-romm-root.target"];
  };

  # Volumes
  systemd.services."podman-volume-romm_mysql_data" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect romm_mysql_data || podman volume create romm_mysql_data
    '';
    partOf = ["podman-compose-romm-root.target"];
    wantedBy = ["podman-compose-romm-root.target"];
  };
  systemd.services."podman-volume-romm_romm_redis_data" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect romm_romm_redis_data || podman volume create romm_romm_redis_data
    '';
    partOf = ["podman-compose-romm-root.target"];
    wantedBy = ["podman-compose-romm-root.target"];
  };
  systemd.services."podman-volume-romm_romm_resources" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect romm_romm_resources || podman volume create romm_romm_resources
    '';
    partOf = ["podman-compose-romm-root.target"];
    wantedBy = ["podman-compose-romm-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-romm-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
